export const FETCH_CART_PRODUCTS_REQUEST = "FETCH_CART_PRODUCTS_REQUEST";
export const FETCH_CART_PRODUCTS_SUCCESS = "FETCH_CART_PRODUCTS_SUCCESS";
export const FETCH_CART_PRODUCTS_FAILURE = "FETCH_CART_PRODUCTS_FAILURE";

export const ADD_PRODUCT_CART_REQUEST = "ADD_PRODUCT_CART_REQUEST";
export const ADD_PRODUCT_CART_SUCCESS = "ADD_PRODUCT_CART_SUCCESS";
export const ADD_PRODUCT_CART_FAILURE = "ADD_PRODUCT_CART_FAILURE";

export const REMOVE_PRODUCT_CART_REQUEST = "REMOVE_PRODUCT_CART_REQUEST";
export const REMOVE_PRODUCT_CART_SUCCESS = "REMOVE_PRODUCT_CART_SUCCESS";
export const REMOVE_PRODUCT_CART_FAILURE = "REMOVE_PRODUCT_CART_FAILURE";

export const INC_PRODUCT_CART_REQUEST = "INC_PRODUCT_CART_REQUEST";
export const DEC_PRODUCT_CART_SUCCESS = "DEC_PRODUCT_CART_SUCCESS";
